let countryList = [
    {country_name: "Afghanistan", country_code: "AF"},
    {country_name: "Åland Islands", country_code: "AX"},
    {country_name: "Albania", country_code: "AL"},
    {country_name: "Algeria", country_code: ""},
    {country_name: "American Samoa", country_code: ""},
    {country_name: "AndorrA", country_code: ""},
    {country_name: "Angola", country_code: ""},
    {country_name: "Anguilla", country_code: ""},
    {country_name: "Antarctica", country_code: ""},
    {country_name: "Antigua and Barbuda", country_code: ""},
    {country_name: "Argentina", country_code: ""},
    {country_name: "Armenia", country_code: ""},
    {country_name: "Aruba", country_code: ""},
    {country_name: "Australia", country_code: ""},
    {country_name: "Austria", country_code: ""},
    {country_name: "Azerbaijan", country_code: ""},
    {country_name: "Bahamas", country_code: ""},
    {country_name: "Bahrain", country_code: ""},
    {country_name: "Bangladesh", country_code: ""},
    {country_name: "Barbados", country_code: ""},
    {country_name: "Belarus", country_code: ""},
    {country_name: "Belgium", country_code: ""},
    {country_name: "Belize", country_code: ""},
    {country_name: "Benin", country_code: ""},
    {country_name: "Bermuda", country_code: ""},
    {country_name: "Bhutan", country_code: ""},
    {country_name: "Bolivia", country_code: ""},
    {country_name: "Bosnia and Herzegovina", country_code: ""},
    {country_name: "Botswana", country_code: ""},
    {country_name: "Bouvet Island", country_code: ""},
    {country_name: "Brazil", country_code: ""},
    {country_name: "British Indian Ocean Territory", country_code: ""},
    {country_name: "Brunei Darussalam", country_code: ""},
    {country_name: "Bulgaria", country_code: ""},
    {country_name: "Burkina Faso", country_code: ""},
    {country_name: "Burundi", country_code: ""},
    {country_name: "Cambodia", country_code: ""},
    {country_name: "Cameroon", country_code: ""},
    {country_name: "Canada", country_code: ""},
    {country_name: "Cape Verde", country_code: ""},
    {country_name: "Cayman Islands", country_code: ""},
    {country_name: "Central African Republic", country_code: ""},
    {country_name: "Chad", country_code: ""},
    {country_name: "Chile", country_code: ""},
    {country_name: "China", country_code: ""},
    {country_name: "Christmas Island", country_code: ""},
    {country_name: "Cocos (Keeling) Islands", country_code: ""},
    {country_name: "Colombia", country_code: ""},
    {country_name: "Comoros", country_code: ""},
    {country_name: "Congo", country_code: ""},
    {country_name: "Congo, The Democratic Republic of the", country_code: ""},
    {country_name: "Cook Islands", country_code: ""},
    {country_name: "Costa Rica", country_code: ""},
    {country_name: "Cote D\'Ivoire", country_code: ""},
    {country_name: "Croatia", country_code: ""},
    {country_name: "Cuba", country_code: ""},
    {country_name: "Cyprus", country_code: ""},
    {country_name: "Czech Republic", country_code: ""},
    {country_name: "Denmark", country_code: ""},
    {country_name: "Djibouti", country_code: ""},
    {country_name: "Dominica", country_code: ""},
    {country_name: "Dominican Republic", country_code: ""},
    {country_name: "Ecuador", country_code: ""},
    {country_name: "Egypt", country_code: ""},
    {country_name: "El Salvador", country_code: ""},
    {country_name: "Equatorial Guinea", country_code: ""},
    {country_name: "Eritrea", country_code: ""},
    {country_name: "Estonia", country_code: ""},
    {country_name: "Ethiopia", country_code: ""},
    {country_name: "Falkland Islands (Malvinas)", country_code: ""},
    {country_name: "Faroe Islands", country_code: ""},
    {country_name: "Fiji", country_code: ""},
    {country_name: "Finland", country_code: ""},
    {country_name: "France", country_code: ""},
    {country_name: "French Guiana", country_code: ""},
    {country_name: "French Polynesia", country_code: ""},
    {country_name: "French Southern Territories", country_code: ""},
    {country_name: "Gabon", country_code: ""},
    {country_name: "Gambia", country_code: ""},
    {country_name: "Georgia", country_code: ""},
    {country_name: "Germany", country_code: ""},
    {country_name: "Ghana", country_code: ""},
    {country_name: "Gibraltar", country_code: ""},
    {country_name: "Greece", country_code: ""},
    {country_name: "Greenland", country_code: ""},
    {country_name: "Grenada", country_code: ""},
    {country_name: "Guadeloupe", country_code: ""},
    {country_name: "Guam", country_code: ""},
    {country_name: "Guatemala", country_code: ""},
    {country_name: "Guernsey", country_code: ""},
    {country_name: "Guinea", country_code: ""},
    {country_name: "Guinea-Bissau", country_code: ""},
    {country_name: "Guyana", country_code: ""},
    {country_name: "Haiti", country_code: ""},
    {country_name: "Heard Island and Mcdonald Islands", country_code: ""},
    {country_name: "Holy See (Vatican City State)", country_code: ""},
    {country_name: "Honduras", country_code: ""},
    {country_name: "Hong Kong", country_code: ""},
    {country_name: "Hungary", country_code: ""},
    {country_name: "Iceland", country_code: ""},
    {country_name: "India", country_code: ""},
    {country_name: "Indonesia", country_code: ""},
    {country_name: "Iran, Islamic Republic Of", country_code: ""},
    {country_name: "Iraq", country_code: ""},
    {country_name: "Ireland", country_code: ""},
    {country_name: "Isle of Man", country_code: ""},
    {country_name: "Israel", country_code: ""},
    {country_name: "Italy", country_code: ""},
    {country_name: "Jamaica", country_code: ""},
    {country_name: "Japan", country_code: ""},
    {country_name: "Jersey", country_code: ""},
    {country_name: "Jordan", country_code: ""},
    {country_name: "Kazakhstan", country_code: ""},
    {country_name: "Kenya", country_code: ""},
    {country_name: "Kiribati", country_code: ""},
    {country_name: "Korea, Democratic People\'S Republic of", country_code: ""},
    {country_name: "Korea, Republic of", country_code: ""},
    {country_name: "Kuwait", country_code: ""},
    {country_name: "Kyrgyzstan", country_code: ""},
    {country_name: "Lao People\'S Democratic Republi", country_code: ""},
    {country_name: "Latvia", country_code: ""},
    {country_name: "Lebanon", country_code: ""},
    {country_name: "Lesotho", country_code: ""},
    {country_name: "Liberia", country_code: ""},
    {country_name: "Libyan Arab Jamahiriya", country_code: ""},
    {country_name: "Liechtenstein", country_code: ""},
    {country_name: "Lithuania", country_code: ""},
    {country_name: "Luxembourg", country_code: ""},
    {country_name: "Macao", country_code: ""},
    {country_name: "Macedonia, The Former Yugoslav Republic of", country_code: ""},
    {country_name: "Madagascar", country_code: ""},
    {country_name: "Malawi", country_code: ""},
    {country_name: "Malaysia", country_code: ""},
    {country_name: "Maldives", country_code: ""},
    {country_name: "Mali", country_code: ""},
    {country_name: "Malta", country_code: ""},
    {country_name: "Marshall Islands", country_code: ""},
    {country_name: "Martinique", country_code: ""},
    {country_name: "Mauritania", country_code: ""},
    {country_name: "Mauritius", country_code: ""},
    {country_name: "Mayotte", country_code: ""},
    {country_name: "Mexico", country_code: ""},
    {country_name: "Micronesia, Federated States of", country_code: ""},
    {country_name: "Moldova, Republic of", country_code: ""},
    {country_name: "Monaco", country_code: ""},
    {country_name: "Mongolia", country_code: ""},
    {country_name: "Montserrat", country_code: ""},
    {country_name: "Morocco", country_code: ""},
    {country_name: "Mozambique", country_code: ""},
    {country_name: "Myanmar", country_code: ""},
    {country_name: "Namibia", country_code: ""},
    {country_name: "Nauru", country_code: ""},
    {country_name: "Nepal", country_code: ""},
    {country_name: "Netherlands", country_code: ""},
    {country_name: "Netherlands Antilles", country_code: ""},
    {country_name: "New Caledonia", country_code: ""},
    {country_name: "New Zealand", country_code: ""},
    {country_name: "Nicaragua", country_code: ""},
    {country_name: "Niger", country_code: ""},
    {country_name: "Nigeria", country_code: ""},
    {country_name: "Niue", country_code: ""},
    {country_name: "Norfolk Island", country_code: ""},
    {country_name: "Northern Mariana Islands'", country_code: ""},
    {country_name: "Norway", country_code: ""},
    {country_name: "Oman", country_code: ""},
    {country_name: "Pakistan", country_code: ""},
    {country_name: "Palau", country_code: ""},
    {country_name: "Palestinian Territory, Occupie", country_code: ""},
    {country_name: "Panama", country_code: ""},
    {country_name: "Papua New Guinea", country_code: ""},
    {country_name: "Paraguay", country_code: ""},
    {country_name: "Peru", country_code: ""},
    {country_name: "Philippines", country_code: ""},
    {country_name: "Pitcairn", country_code: ""},
    {country_name: "Poland", country_code: ""},
    {country_name: "Portugal", country_code: ""},
    {country_name: "Puerto Rico", country_code: ""},
    {country_name: "Qatar", country_code: ""},
    {country_name: "Reunion", country_code: ""},
    {country_name: "Romania", country_code: ""},
    {country_name: "Russian Federation", country_code: ""},
    {country_name: "RWANDA", country_code: ""},
    {country_name: "Saint Helena", country_code: ""},
    {country_name: "Saint Kitts and Nevis", country_code: ""},
    {country_name: "Saint Lucia", country_code: ""},
    {country_name: "Saint Pierre and Miquelon", country_code: ""},
    {country_name: "Saint Vincent and the Grenadines", country_code: ""},
    {country_name: "Samoa", country_code: ""},
    {country_name: "San Marino", country_code: ""},
    {country_name: "Sao Tome and Principe", country_code: ""},
    {country_name: "Saudi Arabia", country_code: ""},
    {country_name: "Senegal", country_code: ""},
    {country_name: "Serbia and Montenegro", country_code: ""},
    {country_name: "Seychelles", country_code: ""},
    {country_name: "Sierra Leone", country_code: ""},
    {country_name: "Singapore", country_code: ""},
    {country_name: "Slovakia", country_code: ""},
    {country_name: "Slovenia", country_code: ""},
    {country_name: "Solomon Islands", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
    {country_name: "", country_code: ""},
]

export {countryList};

